--liquibase formatted sql

--changeset stimur1709:001-create-resources
CREATE TABLE resources
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(100)             NOT NULL,
    type       VARCHAR(30)              NOT NULL,
    status     VARCHAR(20)              NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT resources_type_check
        CHECK (type IN ('NETWORK_DEVICE', 'SERVER', 'DATABASE', 'OTHER')),
    CONSTRAINT resources_status_check
        CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

