package com.github.stimur1709.cloudops.task;

public enum TaskErrorCode {
    SSH_CREDENTIAL_NOT_CONFIGURED,
    SSH_CREDENTIAL_ERROR,
    SSH_CONNECTION_ERROR,
    SSH_HOST_KEY_ERROR,
    SSH_AUTHENTICATION_ERROR,
    SSH_EXECUTION_ERROR,
    COMMAND_TIMEOUT,
    RESOURCE_INACTIVE,
    RESOURCE_UNSUPPORTED,
    HANDLER_NOT_FOUND,
    EXECUTION_ERROR,
    RETRY_EXHAUSTED,
    RECOVERY_EXHAUSTED
}
