### Create resource
POST http://localhost:8080/api/resources
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "service-01",
  "type": "SERVICE",
  "status": "ACTIVE",
  "organizationId": 1,
  "config": {
    "url": "https://httpbin.io/status/200",
    "expectedStatus": 200
  }
}

> {%
    client.global.set("serviceResourceId", response.body.id);
%}

### Create host resource for DNS_CHECK and PING
POST http://localhost:8080/api/resources
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "network-probes-server",
  "type": "SERVER",
  "status": "ACTIVE",
  "organizationId": 1,
  "config": {
    "host": "localhost",
    "sshPort": 22
  }
}

> {%
    client.global.set("networkProbeResourceId", response.body.id);
%}

### Create HTTPS resource for DNS_CHECK, PING and TLS_CHECK
POST http://localhost:8080/api/resources
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "tls-service",
  "type": "SERVICE",
  "status": "ACTIVE",
  "organizationId": 1,
  "config": {
    "url": "https://example.com",
    "expectedStatus": 200
  }
}

> {%
    client.global.set("tlsResourceId", response.body.id);
%}

### Get resource
GET http://localhost:8080/api/resources/1
Authorization: Bearer {{accessToken}}

### Search resources
POST http://localhost:8080/api/resources/search
Authorization: Bearer {{accessToken2}}
Content-Type: application/json

{
  "start": 0,
  "size": 20,
  "filter": {
    "operator": "AND",
    "conditions": [
      {
        "field": "name",
        "operation": "EQ",
        "value": "router-01"
      }
    ]
  },
  "sort": [
    {
      "field": "createdAt",
      "order": "DESC"
    }
  ],
  "getTotal": true
}

### Update resource
PUT http://localhost:8080/api/resources/1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "router-01",
  "type": "NETWORK_DEVICE",
  "status": "INACTIVE",
  "organizationId": 1,
  "config": {
    "host": "10.0.0.1",
    "managementPort": 2222
  }
}

### Delete resource
DELETE http://localhost:8080/api/resources/1
Authorization: Bearer {{accessToken}}
