### Create resource
POST http://localhost:8080/api/resources
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "service-03",
  "type": "SERVICE",
  "status": "ACTIVE",
  "organizationId": 1,
  "config": {
    "url": "https://httpbin.io/status/200",
    "expectedStatus": 200,
    "timeoutMs": 5000
  }
}

### Get resource
GET http://localhost:8080/api/resources/1
Authorization: Bearer {{accessToken}}

### Search resources
POST http://localhost:8080/api/resources/search
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "start": 0,
  "size": 20,
  "filter": {
    "operator": "AND",
    "conditions": [
      {
        "field": "name",
        "operation": "EQ",
        "value": "router-01"
      }
    ]
  },
  "sort": [
    {
      "field": "createdAt",
      "order": "DESC"
    }
  ],
  "getTotal": true
}

### Update resource
PUT http://localhost:8080/api/resources/1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "router-01",
  "type": "NETWORK_DEVICE",
  "status": "INACTIVE",
  "organizationId": 1,
  "config": {
    "host": "10.0.0.1",
    "managementPort": 2222
  }
}

### Delete resource
DELETE http://localhost:8080/api/resources/1
Authorization: Bearer {{accessToken}}
