### Create resources task
POST http://localhost:8080/api/resources/4/tasks
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "type": "HTTP_CHECK"
}

> {%
    client.global.set("taskId", response.body.id);
%}

### Get current task state/result
GET http://localhost:8080/api/tasks/{{taskId}}
Authorization: Bearer {{accessToken}}
