package com.github.stimur1709.cloudops.probe;

public enum ProbeErrorCode {
    TIMEOUT,
    DNS_ERROR,
    CONNECTION_ERROR,
    SSH_HANDSHAKE_ERROR,
    SSH_AUTHENTICATION_ERROR,
    SSH_HOST_KEY_ERROR,
    CREDENTIAL_NOT_CONFIGURED,
    CREDENTIAL_ERROR,
    TLS_ERROR,
    HTTP_CLIENT_ERROR
}
